@baseUrl = https://api.unsplash.com

### Search for photo
GET {{baseUrl}}/search/photos
Accept: application/hal+json

### 
GET {{baseUrl}}/search/users?page=1&query=nas
Authorization: 00ad9b56c5998633216cab9393e30c6b97a6e3ba4bff0061c11b243c0144993f

### Get Users
GET https://api.github.com/users/VictorTolbert

### JSON Server Users
GET http://localhost:3000/users


### Github Commits
https://api.github.com/repos/Gitart/work/commits

### Github Gists
https://api.github.com/users/Gitart/gists

### Github Subscriptions
https://api.github.com/users/Gitart/subscriptions
