// import "./fontawesome";
import './alerts'
import './bars'
import './buefy'
import './carousel'
import './clipboard'
import './date-fns'
import './frappe-charts'
import './global'
import './http'
import './portal'
import './scroll-reveal'
import './tippy'
import './tooltips'
import './trend'
